apiVersion: apps/v1
kind: Deployment
metadata:
  name: smashshop-backend-deployment
  namespace: application-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smashshop-backend
  template:
    metadata:
      labels:
        app: smashshop-backend
    spec:
      containers:
      - name: smashshop-backend
<<<<<<< HEAD
        image: nhannh/smash-shop-backend-image:37
=======
        image: nhannh/smash-shop-backend-image:44
>>>>>>> 76b6d336e991fa6fff8644f0df7fc497af1e8fdb
        ports:
        - containerPort: 5001
        envFrom:
        - secretRef:
            name: smashshop-backend-secret
