apiVersion: apps/v1
kind: Deployment
metadata:
  name: smashshop-frontend-deployment
  namespace: application-deployment
  labels:
    app: smashshop-frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: smashshop-frontend
  template:
    metadata:
      labels:
        app: smashshop-frontend
    spec:
      containers:
        - name: smashshop-frontend
          image: nhannh/smash-shop-frontend-image:56
          # Bổ sung Port để K8s quản lý
          ports:
            - containerPort: 30444
          envFrom:
            - secretRef:
                name: smashshop-frontend-secret
          env:
            - name: REACT_APP_API_URL
              value: "https://192.168.13.128:30444"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: ssl-certs
              mountPath: /etc/nginx/ssl/smashshop.com
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: frontend-nginx-config
            items:
              - key: default.conf
                path: default.conf
        - name: ssl-certs
          secret:
            secretName: frontend-tls-secret
            items:
              - key: tls.crt
                path: smashshop.com.crt
              - key: tls.key
                path: smashshop.com.key