apiVersion: apps/v1
kind: Deployment
metadata:
  name: smashshop-frontend-deployment
  namespace: application-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smashshop-frontend
  template:
    metadata:
      labels:
        app: smashshop-frontend
    spec:
      containers:
      - name: smashshop-frontend
        image: nhannh/smash-shop-frontend-image:36
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: smashshop-frontend-secret
        env:
        - name: REACT_APP_API_URL
          value: "http://192.168.13.128:30003"
